link-message:
  - "spigot https://www.spigotmc.org/resources/linkblockpl.124730/"
  - "<gradient:#ff0000,#ffff00>▶ Наш телеграм: https://t.me/example</gradient>"
  - "&9▶ Наш дискорд: &fhttps://discord.gg/example"
  - "<gradient:#00ff00,#00ffff,#0000ff>⬆ Подпишись, чтобы не пропустить новости!</gradient>"
  - "&b▶ Наш телеграм: &fhttps://t.me/example"
  - "&9▶ Наш дискорд: &fhttps://discord.gg/example"
  - "&a⬆ Подпишись, чтобы не пропустить новости!"
  - "<gradient:#ff0000,#ffff00>▶ Наш телеграм: https://t.me/example</gradient>"
  - "&9▶ Наш дискорд: &fhttps://discord.gg/example"
  - "<gradient:#00ff00,#00ffff,#0000ff>⬆ Подпишись, чтобы не пропустить новости!</gradient>"
#Спасибо что скачали плагин