name: LinkBlockPl
main: com.example.linkblockpl.Main
version: 1.2
api-version: 1.16
commands:
  mylink:
    description: Показывает ссылку и перезагружает конфиг
    usage: /mylink reload
  link:
    description: Показывает кликабельную ссылку
    usage: /link
permissions:
  mylink.reload:
    description: Позволяет перезагружать конфигурацию
    default: op